In [1]:
import numpy as np
import torch
import torchvision
import torchvision.transforms as transforms

## 一、PyTorch基本操作考察

1. 用Tensor初始化一个1x3 的矩阵M和一个2x1的矩阵N，对两矩阵进行减法操作（要求实现三种不同的形式），给出结果并分析三种方式的不同（如果出现报错，分析报错的原因），同时需要指出在计算过程中发生了什么

In [ ]:
M = torch.zeros((1, 3))
N = torch.ones((2, 1))

In [2]:
t = M - N
t

tensor([[-1., -1., -1.],
        [-1., -1., -1.]])

In [4]:
t = torch.sub(M, N)
t

tensor([[-1., -1., -1.],
        [-1., -1., -1.]])

In [6]:
t = torch.add(M, -N)
t

tensor([[-1., -1., -1.],
        [-1., -1., -1.]])

2. ①利用Tensor创建两个大小分别3x2 和4x2的随机数矩阵P和Q，要求服从均值为0，标准差0.01为的正态分布；②对第二步得到的矩阵Q进行形状变换得到Q的转置QT；③对上述得到的矩阵P和矩阵QT求矩阵相乘

In [7]:
P = torch.zeros((3, 2))
Q = torch.zeros((4, 2))

P = torch.normal(P, 0.01)
Q = torch.normal(Q, 0.01)

In [8]:
P

tensor([[-0.0069, -0.0179],
        [ 0.0086,  0.0057],
        [-0.0082, -0.0004]])

In [9]:
Q

tensor([[-0.0035, -0.0010],
        [ 0.0042, -0.0114],
        [-0.0040,  0.0021],
        [-0.0039,  0.0024]])

In [12]:
QT = Q.T
QT

tensor([[-0.0035,  0.0042, -0.0040, -0.0039],
        [-0.0010, -0.0114,  0.0021,  0.0024]])

In [13]:
torch.mm(P, QT)

tensor([[ 4.2152e-05,  1.7581e-04, -1.0506e-05, -1.6401e-05],
        [-3.6047e-05, -2.9239e-05, -2.2230e-05, -1.9844e-05],
        [ 2.9159e-05, -3.0390e-05,  3.1911e-05,  3.1166e-05]])

3. 给定公式 $y_3 = y_1+y_2=x^2+x^3$，且$x=1$。利用学习所得到的Tensor的相关知识，求$y_3$对$x$的梯度。要求在计算过程中，在计算$x^3$时中断梯度的追踪，观察结果并进行原因分析

In [21]:
x = torch.tensor(1.0, requires_grad=True)
x

tensor(1., requires_grad=True)

In [24]:
y1 = torch.pow(x, 2)
y2 = torch.pow(x, 3)
y3 = torch.add(y1, y2)

In [27]:
y3.backward()

In [28]:
x.grad

tensor(5.)

若在计算 $x^3$ 时中断梯度的跟踪

In [30]:
x = torch.tensor(1.0, requires_grad=True)
y1 = torch.pow(x, 2)
with torch.no_grad():
    y2 = torch.pow(x, 3)
y3 = torch.add(y1, y2)
y3.backward()
x.grad

tensor(2.)

原因是：
![](assets/1-1.png)